# Generated by Django 4.0.4 on 2022-05-04 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='duration',
        ),
    ]
